# Site settings
title: Tomas Ondrias
description: "Tomas Ondrias is a graduate of opera singing at the Academy of Performing Arts in Bratislava. He worked with Opernfestspielen St. Margarethen (2012), Operettenfestspielen Bad Hall (2014) under the baton of conductors as Alfred Eschwé, Gustav Kuhn and Gergard Lagrange. While studying at the Academy of Performing Arts he is presented within opera studies as Don Asdrubale and Pulcherio in Mozart's opera Lo Sposo Deluso. He interprets classic songs, opera, operetta and pop opera (operatic pop). As a soloist he sings in vocal-instrumental ensemble Cavalieri, which is mainly devoted to the interpretation of the operetta genre in its specific arrangement. As a soloist he regularly participates in the Slovak National Song Festival, organized by the Matica Slovenská. Tomas Ondrias is an active performer and singer at many events in Slovakia and abroad."
baseurl: ""
url: "http://tomasondrias.com"
email: tomas.ondrias@gmail.com
facebook_username:  tomasondrias
youtube_username:  1987soso1987
twitter_username: TomasOndrias
instagram_username: tomiondrias_tenor

# Build settings
markdown: kramdown
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
